### ISSUE TITLE
Wiki is missing important installation step

### ISSUE THREAD

**Issue by jwilling** [davechurchill/ualbertabot#7] opened 2015-04-22 08:28 UTC
First of all, thanks for the awesome project! Very cool to see something like this working on one of my favorite games. I was trying to get the UAlbertaBot functioning, and after following the installation steps exactly as written in the wiki it gave me an error that `libgmp-10.dll` was missing.

I'm quite unfamiliar with Windows development, so this might be a non-issue, but I wasn't able to get it running. I poked around until I found a couple of DLLs in the `bwta2/windows` directory, which contained `libgmp-10.dll` and `libmpfr-4.dll`. After copying these manually to the Windows directory, things seemed to run smoothly.

Is this a reasonable solution to this problem? If so, I would be happy to update the wiki to reflect this step. Thanks again!

**Comment by davechurchill** [comment] 2015-09-16 19:54
I closed this because the issue is solved by following the instructions when installing BWTA2. I will note it on the wiki, thanks!

**Closed as completed by davechurchill** 2015-09-16 19:54 UTC

**Comment by louisrousseau** [comment] 2016-03-23 06:40
The BWTA2 instructions should be corrected: the DLLs don't have to be in the Windows directory. (I'll go one step further and say that they shouldn't.)

So long as the files are in a directory accessible listed in the PATH environment variable you should be good to go. The user or system PATH environment variable should work (I appended to the system one, confirmed working) as well as feeding the information to Chaoslauncher via a batch file that modifies the PATH variable locally prior to launch.
